### ISSUE TITLE
README is really long

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#105]
The readme could be improved by having collapsable sections or making the examples collapsible. Maybe splitting some of the sections out into separate files that are links from the README would be good too?.

**Comment by Okabe-Junya** [comment]
This proposal seems excellent!! 

Structuring the README is a great idea. Since this repository is included within a GitHub Organization, if there's a preferred approach within the organization, we might be able to follow it.

From what I've researched, the method used in the [CodeQL repo](https://github.com/github/codeql/tree/main/docs) appears to be commendable.

**Comment by MihirKohli** [comment]
Is this issue still available if yes then can you assign me?

**Comment by MihirKohli** [comment]
Thank for assigning, will sure do ask if needed any help

**Comment by MihirKohli** [comment]
> @MihirKohli I've added you as the assignee. Thanks for volunteering to take this one on. Let me know if there is any support I can offer you.

Should I structure README similarly to the CodeQL Repo by separating it into sections?

**Comment by MihirKohli** [comment]
> > Thank for assigning, will sure ask if needed any help
> 
> Hey @MihirKohli Can we work on it together?

I have already worked on it, meanwhile you can checkout other issue's.

**Comment by MihirKohli** [comment]
> > Thank for assigning, will sure ask if needed any help
> 
> Hey @MihirKohli Can we work on it together?

I have already worked upon it.

**Comment by MihirKohli** [comment]
@zkoppert https://github.com/github/issue-metrics/pull/131
