### ISSUE TITLE
feat: Add the result images in the README.

### ISSUE THREAD

**Issue by Okabe-Junya** [github/issue-metrics#150]
## Desired Feature

Add a captured image of an actual issue being created to the README. This will likely be very helpful for first-time users of this action and on the GitHub Marketplace.

## Related

- https://github.com/github/issue-metrics/issues/142#issuecomment-1762822496
- https://github.com/github/issue-metrics/issues/142#issuecomment-1769423407

**Comment by Okabe-Junya** [comment]
We might have several things to consider:

- Which repo's created issue should we capture? (Probably this repo?)
- What should be the size of the capture?
- I use dark mode, but should we avoid using dark mode when capturing?

**Comment by spier** [comment]
I suggest to run the "getting started" workflow on this repo itself for e.g. the month of September 2023, and then take a screenshot of that. If that results in too many issues in the issue table, either cut that off in the screenshot a bit, or pick another month that has a smaller amount of issues/prs.

Also is the different in output for issues vs PRs significant enough to warrant a screenshot for each?
Or will one screenshot do?

**Comment by zkoppert** [comment]
I think one screenshot will do just to give folks an idea of the output. The action run on this repo would be good.

I'd aim for making the capture size around (doesn't have to be exact) 

> Height - 720 pixels
> Width - 1280 pixels
> Aspect ratio - 16:9
> PPI - 72

source: https://tiny-img.com/blog/best-image-size-for-website/

I think getting a light mode image would be best (I use dark mode as well, but since the docs.github.com folks use light mode, probably best to match)

**Comment by spier** [comment]
Pasting some examples here for possible screenshots.

# Issue Metrics

| Metric | Average | Median | 90th percentile |
| --- | --- | --- | ---: |
| Time to first response | 4 days, 17:53:36 | 12:53:42 | 13 days, 11:55:44 |
| Time to close | 2 days, 5:51:27 | 1 day, 7:49:24 | 5 days, 1:10:09 |
| Time to answer | None | None | None |
| Time spent in bla | None | None | None |

| Metric | Count |
| --- | ---: |
| Number of items that remain open | 4 |
| Number of items closed | 4 |
| Total number of items created | 8 |

| Title | URL | Author | Time to first response | Time to close | Time to answer | Time spent in bla |
| --- | --- | --- | --- | --- | --- | --- |
| Is the generated table too long? | https://github.com/github/issue-metrics/issues/132 | Okabe-Junya | 26 days, 3:57:53 | None | None | None |
| `make test` doesn't work | https://github.com/github/issue-metrics/issues/130 | Okabe-Junya | None | 0:30:06 | None | None |
| Add author line for result in pull-requests | https://github.com/github/issue-metrics/issues/128 | ostk0069 | 7:51:45 | 6 days, 7:16:53 | None | None |
| Feature: Create metrics using project status of an issue | https://github.com/github/issue-metrics/issues/120 | SqaDomovik | 13:59:05 | None | None | None |
| I'v got "The search query is invalid; Check the search query." | https://github.com/github/issue-metrics/issues/119 | theMistletoe | 1:50:55 | 2 days, 2:54:27 | None | None |
| "Who are we helping" metric | https://github.com/github/issue-metrics/issues/115 | MaineC | 19:53:36 | None | None | None |
| Option to include number of very active reviewers in report | https://github.com/github/issue-metrics/issues/114 | MaineC | 11:48:20 | None | None | None |
| Extended make lint Execution Time | https://github.com/github/issue-metrics/issues/112 | Okabe-Junya | None | 12:44:22 | None | None |

_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
Search query used to find these items: `repo:github/issue-metrics is:issue created:2023-09-01..2023-09-30 -reason:"not planned"`

# Issue Metrics

| Metric | Average | Median | 90th percentile |
| --- | --- | --- | ---: |
| Time to first response | 1 day, 22:38:43 | 22:44:40 | 4 days, 5:27:16 |
| Time to close | 2 days, 7:42:27 | 2 days, 1:43:08 | 5 days, 10:42:25 |
| Time to answer | None | None | None |
| Time spent in enhancement | 8 days, 7:58:50 | 4 days, 1:50:38 | 19 days, 1:20:18 |
| Time spent in good first issue | None | None | None |

| Metric | Count |
| --- | ---: |
| Number of items that remain open | 0 |
| Number of items closed | 15 |
| Total number of items created | 15 |

| Title | URL | Author | Time to first response | Time to close | Time to answer | Time spent in enhancement | Time spent in good first issue |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Updated Readme | https://github.com/github/issue-metrics/pull/131 | MihirKohli | 5 days, 10:16:35 | None | None | None | None |
| feat: add author column | https://github.com/github/issue-metrics/pull/129 | Okabe-Junya | 5:20:28 | 5 days, 23:10:22 | None | 5 days, 17:58:43 | None |
| Support more than one statistic for summarizing time lists | https://github.com/github/issue-metrics/pull/127 | MaineC | 3 days, 4:08:19 | 3 days, 4:09:02 | None | 24 days, 18:12:25 | None |
| Restructure README.md | https://github.com/github/issue-metrics/pull/126 | rajveer43 | 15:36:18 | 6 days, 9:40:18 | None | None | None |
| Documentation: Add required python version to docs and test deps. | https://github.com/github/issue-metrics/pull/125 | MaineC | 4:53:52 | 4:55:23 | None | None | None |
| Correct pip command name | https://github.com/github/issue-metrics/pull/123 | zkoppert | None | 0:49:33 | None | None | None |
| Exclude bot's comment from "Time to first response" | https://github.com/github/issue-metrics/pull/121 | eichisanden | 2 days, 16:58:38 | 3 days, 3:01:29 | None | 10:01:39 | None |
| Create pull_request-template.md | https://github.com/github/issue-metrics/pull/118 | zkoppert | None | 5:46:46 | None | None | None |
| linting fixes | https://github.com/github/issue-metrics/pull/116 | zkoppert | None | 0:03:50 | None | None | None |
| update: Makefile, .pylintrc | https://github.com/github/issue-metrics/pull/113 | Okabe-Junya | 12:38:51 | 12:39:50 | None | None | None |
| Feature: Ignore PR time spent as draft, measure PRs by merge time | https://github.com/github/issue-metrics/pull/111 | PressXtoChris | 11:51:36 | 2 days, 21:33:08 | None | 2 days, 9:42:32 | None |
| build(deps): bump pytz from 2023.3 to 2023.3.post1 | https://github.com/github/issue-metrics/pull/109 | dependabot[bot] | 5:56:09 | 5:56:14 | None | None | None |
| build(deps): bump actions/checkout from 3 to 4 | https://github.com/github/issue-metrics/pull/108 | dependabot[bot] | 1 day, 5:53:01 | 1 day, 5:53:09 | None | None | None |
| docs: update: Ability to send a list of repos instead of just one | https://github.com/github/issue-metrics/pull/107 | Okabe-Junya | 4 days, 4:37:59 | 4 days, 4:38:03 | None | None | None |
| docs(readme): document how to ignore bots | https://github.com/github/issue-metrics/pull/106 | azamb | 4 days, 5:32:45 | 4 days, 5:37:13 | None | None | None |

_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
Search query used to find these items: `repo:github/issue-metrics is:pr created:2023-09-01..2023-09-30 -reason:"not planned"`

# Issue Metrics

| Metric | Average | Median | 90th percentile |
| --- | --- | --- | ---: |
| Time to first response | 2:13:08 | 2:14:10 | 3:55:18 |
| Time to close | 4 days, 11:28:30 | 4 days, 11:28:30 | 4 days, 11:28:30 |
| Time to answer | None | None | None |
| Time spent in enhancement | None | None | None |

| Metric | Count |
| --- | ---: |
| Number of items that remain open | 3 |
| Number of items closed | 1 |
| Total number of items created | 4 |

| Title | URL | Author | Time to first response | Time to close | Time to answer | Time spent in enhancement |
| --- | --- | --- | --- | --- | --- | --- |
| Monthly contributor report | https://github.com/github/issue-metrics/issues/151 | github-actions[bot] | 0:01:37 | None | None | None |
| feat: Add the result images in the README. | https://github.com/github/issue-metrics/issues/150 | Okabe-Junya | 4:22:38 | None | None | None |
| Formatting of stats output | https://github.com/github/issue-metrics/issues/144 | spier | 2:51:32 | None | None | None |
| [docs] Simple example in main README? | https://github.com/github/issue-metrics/issues/142 | spier | 1:36:47 | 4 days, 11:28:30 | None | None |

_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
Search query used to find these items: `repo:github/issue-metrics is:issue created:2023-10 -reason:"not planned"`

# Issue Metrics

| Metric | Average | Median | 90th percentile |
| --- | --- | --- | ---: |
| Time to first response | 2 days, 19:37:07 | 11:30:54 | 7 days, 0:18:08 |
| Time to close | 7 days, 7:05:52 | 1 day, 11:56:07 | 19 days, 2:41:27 |
| Time to answer | None | None | None |
| Time spent in enhancement | 26 days, 13:39:31 | 18 days, 2:19:33 | 55 days, 11:46:58 |

| Metric | Count |
| --- | ---: |
| Number of items that remain open | 1 |
| Number of items closed | 11 |
| Total number of items created | 12 |

| Title | URL | Author | Time to first response | Time to close | Time to answer | Time spent in enhancement |
| --- | --- | --- | --- | --- | --- | --- |
| Table columns break when PR title contains vertical bar ( &#124; ) | https://github.com/github/issue-metrics/issues/79 | vibin | 1 day, 0:26:45 | 1 day, 1:14:28 | None | None |
| Is repo required? | https://github.com/github/issue-metrics/issues/67 | stnguyen90 | 21:18:57 | 22:44:08 | None | None |
| Feature: Filter Out CI User Responses from Time to First Response | https://github.com/github/issue-metrics/issues/65 | philnielsen | 1:07:55 | 11 days, 2:37:11 | None | 11 days, 1:30:01 |
| README workflow example misses the issues:write permission | https://github.com/github/issue-metrics/issues/60 | julioz | 6:57:42 | 6:59:51 | None | None |
| Search query for PRs returns metrics for issues | https://github.com/github/issue-metrics/issues/59 | paul-uz | 8:42:04 | 1 day, 10:54:07 | None | None |
| Integration with V2 Projects | https://github.com/github/issue-metrics/issues/57 | e0d | 1:01:44 | None | None | 91 days, 20:12:54.898976 |
| Better install instructions | https://github.com/github/issue-metrics/issues/53 | paul-uz | 4:17:53 | 10:22:08 | None | None |
| Assign members of a GitHub team handle in addition of individuals | https://github.com/github/issue-metrics/issues/52 | julioz | 14:19:43 | 1 day, 11:56:07 | None | 1 day, 4:14:01 |
| Document that search results are limited to 1000 results | https://github.com/github/issue-metrics/issues/51 | zkoppert | 5 days, 16:07:52 | 8 days, 3:16:28 | None | None |
| feat: README example that demonstrates multiple search queries with 1 report | https://github.com/github/issue-metrics/issues/49 | zkoppert | 19 days, 1:50:33 | 19 days, 2:41:27 | None | 19 days, 2:41:27 |
| feat: Include link to action in the markdown | https://github.com/github/issue-metrics/issues/47 | zkoppert | None | 17 days, 1:57:39 | None | 17 days, 1:57:39 |
| feat: Include search query in the metrics report markdown/json | https://github.com/github/issue-metrics/issues/46 | zkoppert | None | 19 days, 3:21:01 | None | 19 days, 3:21:01 |

_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
Search query used to find these items: `repo:github/issue-metrics is:issue created:2023-07-01..2023-07-31 -reason:"not planned"`

**Comment by Okabe-Junya** [comment]
Thank you for sharing some examples.

While these examples are great, capturing at 720 x 1280 might be a bit challenging. How should we go about capturing?

**Comment by Okabe-Junya** [comment]
> If that results in too many issues in the issue table, either cut that off in the screenshot a bit, or pick another month that has a smaller amount of issues/prs.

You might be right, choosing a different month for the query might be better (for instance, the results from July or August might be suitable).

**Comment by spier** [comment]
I agree, 720x1280 will be hard for the tabular format that this GHA produces :)

I am already working on a PR. Almost ready. Let's review that together then and decide if we like it or not.

**Comment by Okabe-Junya** [comment]
Fantastic!

I'm looking forward to the PR. If needed, I can also help with the review. Just mention me when the time comes.
