### ISSUE TITLE
Time to answer is not calculated, indicated as None for all issues

### ISSUE THREAD

**Issue by Piedone** [github/issue-metrics#188]
I've used the action to calculate `repo:OrchardCMS/OrchardCore is:issue created:2023-12-01..2023-12-31 -reason:"not planned"` but the "Time to answer" column is None for every issue:

![image](https://github.com/github/issue-metrics/assets/1976647/60c2ed51-ea5d-474c-a3bb-3265de8f5d2d)

Note how the aggregated metrics at the top also show "Time to answer" as None for all three columns.

Almost every issue listed here had an answer (from a core contributor) within the same time period.

The same issue exists for PRs too. There BTW an approval should also be considered an answer I'd say.

**Comment by zkoppert** [comment]
Hi! Time to answer is only applicable to discussions since a post in a comment can be marked as "answered". If you would like, you can hide the time to answer stat with the `HIDE_TIME_TO_ANSWER` variable with more details in the [configuration section of the README](https://github.com/github/issue-metrics?tab=readme-ov-file#configuration).

**Comment by Piedone** [comment]
Thank you for your quick reply! Ah, I see, I missed that. Then all is good, thank you. Works great:

- https://github.com/OrchardCMS/OrchardCore/issues/15055
- https://github.com/OrchardCMS/OrchardCore/issues/15056
