### ISSUE TITLE
Feature: Ability to send a list of repos instead of just one

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#26]
It would be nice to feed it a list of repositories instead of just one repo. The use case for this would be: As a maintainer, I want to check my response rate and close rate for issues and PRs in open source projects that I maintain.

**Comment by Okabe-Junya** [comment]
Hi!!

I added this example to the README in #93, but do you mean to provide this within the CI workflow? I might be able to work on this issue. (It might take me some time, though...)

**Comment by zkoppert** [comment]
Yes, Here I am talking about being able to do this in the search query like this. GitHub search has this nice `OR` capability so I thought it would be good to add an example of using this to the readme:
`SEARCH_QUERY: repo:github-linguist/linguist OR repo:tree-sitter/tree-sitter is:issue`

**Comment by Okabe-Junya** [comment]
Hi!!!

I apologize for the considerable delay in my response, as I didn't notice the notification for this issue.

[The link you commented on](https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax#repository-qualifier) seems quite valuable, but it looks like a syntax for a **code** search query. We might want to consult documents like [this](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) because our aim is to search for issues. To "OR" multiple repos, perhaps you can simply list the repo names in the query.

Here's a simple example.

Search query: `repo:Okabe-Junya/sandbox repo:Okabe-Junya/dotfiles is:issue created:2022-07-01..2023-07-31 -reason:"not planned"` resulted in https://github.com/Okabe-Junya/sandbox/issues/218 (most of them are in Japanese, though).

I can create a PR to fix #93. This method appears to be more efficient.

Thank you.

**Comment by Okabe-Junya** [comment]
> As a maintainer, I want to check my response rate and close rate for issues and PRs in open source projects that I maintain.

For your purpose, the "involve" operator might be very useful.

[Search by a user that's involved in an issue or pull request](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request)
