### ISSUE TITLE
feat: README example that demonstrates multiple search queries with 1 report

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#49]
README example that demonstrates multiple search queries with 1 report

Use case: I want to be able to run different searches in different repositories and report on the metrics in a single markdown report
Use case: I want to be able to see both open and closed issues over a certain time period

This could look like feeding the action a list of SEARCH_QUERYs or a workflow file that ties together several json outputs to create a single markdown report.

**Comment by Okabe-Junya** [comment]
Hi!

I have created a workflow to accomplish this and inspected that it works well in a sandbox environment. I'd like to send a PR later.

![Screenshot 2023-08-03 at 4 07 21](https://github.com/github/issue-metrics/assets/86868255/cde69a0f-2f1d-4986-97d7-508505e6c391)

During inspection in my sandbox repo, I accidentally attached several reference comments to the issue because I was collecting metrics from [this repo](https://github.com/github/issue-metrics). (This is how it appears from my environment.) 

![Screenshot 2023-08-03 at 4 16 56](https://github.com/github/issue-metrics/assets/86868255/685aebde-08f5-46e5-831a-6ddee6758d5f)

This is not ideal, so I made my sandbox repo private, but if it's no problem, I would like to make it public again. (It's certainly not malicious spam.)

I hope the PR will be merged.
